FROM lacion/docker-alpine:gobuildimage

LABEL app="build-statg-server"
LABEL REPO="https://github.com/statsg/statsg"

ENV GOROOT=/usr/lib/go \
    GOPATH=/gopath \
    GOBIN=/gopath/bin \
    PROJPATH=/gopath/src/github.com/statsg/statsg

# Because of https://github.com/docker/docker/issues/14914
ENV PATH=$PATH:$GOROOT/bin:$GOPATH/bin

WORKDIR /gopath/src/github.com/statsg/statsg

CMD ["make","build-alpine"]